language: php

dist: precise

sudo: false

matrix:
  include:
    - php: 5.3
      env: DB=PGSQL CORE_RELEASE=3.4
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=3.5
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=3
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=3

before_script:
 - composer self-update || true
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - vendor/bin/phpunit framework/tests
